<a href="https://colab.research.google.com/github/iamgiribabu/cencus_income/blob/main/Cencus_income.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [9]:
dataframe = pd.read_csv("/content/drive/MyDrive/Dataset/cencus_income.csv",
                        skipinitialspace=True,
                        na_values='?')

In [10]:
dataframe

age workclass  fnlwgt     education  education.num      marital.status  \
0       90       NaN   77053       HS-grad              9             Widowed   
1       82   Private  132870       HS-grad              9             Widowed   
2       66       NaN  186061  Some-college             10             Widowed   
3       54   Private  140359       7th-8th              4            Divorced   
4       41   Private  264663  Some-college             10           Separated   
...    ...       ...     ...           ...            ...                 ...   
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
0                    NaN  Not-in-family  White  Female             0   
1        Exec-managerial  Not-in-family  White  Female             0   
2                    NaN      Unmarried  Black  Female             0   
3      Machine-op-inspct      Unmarried  White  Female             0   
4         Prof-specialty      Own-child  White  Female             0   
...                  ...            ...    ...     ...           ...   
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
0              4356              40  United-States  <=50K  
1              4356              18  United-States  <=50K  
2              4356              40  United-States  <=50K  
3              3900              40  United-States  <=50K  
4              3900              40  United-States  <=50K  
...             ...             ...            ...    ...  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K  

[32561 rows x 15 columns]

In [11]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  31978 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [12]:
print(dataframe['workclass'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['occupation'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['education'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['relationship'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['race'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['sex'].value_counts(normalize=True)*100)
print('-'*50)
print(dataframe['native.country'].value_counts(normalize=True)*100)

workclass
Private             73.868186
Self-emp-not-inc     8.270138
Local-gov            6.812042
State-gov            4.224573
Self-emp-inc         3.632221
Federal-gov          3.124491
Without-pay          0.045566
Never-worked         0.022783
Name: proportion, dtype: float64
--------------------------------------------------
occupation
Prof-specialty       13.477440
Craft-repair         13.343968
Exec-managerial      13.236539
Adm-clerical         12.272934
Sales                11.882284
Other-service        10.726610
Machine-op-inspct     6.517351
Transport-moving      5.198906
Handlers-cleaners     4.459926
Farming-fishing       3.235888
Tech-support          3.021030
Protective-serv       2.112768
Priv-house-serv       0.485058
Armed-Forces          0.029299
Name: proportion, dtype: float64
--------------------------------------------------
education
HS-grad         32.250238
Some-college    22.391818
Bachelors       16.446055
Masters          5.291607
Assoc-voc        4.2443

In [13]:
dataframe.rename(columns={"education.num ": "education_num",
                          "capital.gain": "capital_gain",
                          "capital.loss": "capital_loss",
                          "hours.per.week": "hours_per_week",
                          "native.country": "native_country",
                          "marital.status": "marital_status",
                          }, inplace=True)

In [14]:
dataframe.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [15]:
# dataframe['workclass'].fillna(dataframe['workclass'].mode()[0], inplace=True)
# dataframe['occupation'].fillna(dataframe['occupation'].mode()[0], inplace=True)
dataframe['native_country'].fillna(dataframe['native_country'].mode()[0], inplace=True)

In [16]:
dataframe.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country       0
income               0
dtype: int64

In [17]:
# !pip install autoviz

In [18]:
# from autoviz.AutoViz_Class import AutoViz_Class
# AV = AutoViz_Class()
# report = AV.AutoViz("/content/cencus_income.csv")

In [19]:
dataframe.dropna(inplace=True)

In [20]:
dataframe.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()

dataframe['workclass'] = labelEncoder.fit_transform(dataframe['workclass'])
dataframe['education'] = labelEncoder.fit_transform(dataframe['education'])
dataframe['marital_status'] = labelEncoder.fit_transform(dataframe['marital_status'])
dataframe['sex'] = labelEncoder.fit_transform(dataframe['sex'])
dataframe['native_country'] = labelEncoder.fit_transform(dataframe['native_country'])
dataframe['race'] = labelEncoder.fit_transform(dataframe['race'])
dataframe['relationship'] = labelEncoder.fit_transform(dataframe['relationship'])
dataframe['occupation'] = labelEncoder.fit_transform(dataframe['occupation'])
dataframe['income'] = labelEncoder.fit_transform(dataframe['income'])

In [22]:
dataframe.head()

age  workclass  fnlwgt  education  education.num  marital_status  \
1   82          2  132870         11              9               6   
3   54          2  140359          5              4               0   
4   41          2  264663         15             10               5   
5   34          2  216864         11              9               0   
6   38          2  150601          0              6               5   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
1           3             1     4    0             0          4356   
3           6             4     4    0             0          3900   
4           9             3     4    0             0          3900   
5           7             4     4    0             0          3770   
6           0             4     4    1             0          3770   

   hours_per_week  native_country  income  
1              18              38       0  
3              40              38       0  
4              40              38       0  
5              45              38       0  
6              40              38       0

In [23]:
x=dataframe.drop('income',axis=1)
y=dataframe['income']

In [24]:
x.shape, y.shape

((30718, 14), (30718,))

In [25]:
x

age  workclass  fnlwgt  education  education.num  marital_status  \
1       82          2  132870         11              9               6   
3       54          2  140359          5              4               0   
4       41          2  264663         15             10               5   
5       34          2  216864         11              9               0   
6       38          2  150601          0              6               5   
...    ...        ...     ...        ...            ...             ...   
32556   22          2  310152         15             10               4   
32557   27          2  257302          7             12               2   
32558   40          2  154374         11              9               2   
32559   58          2  151910         11              9               6   
32560   22          2  201490         11              9               4   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
1               3             1     4    0             0          4356   
3               6             4     4    0             0          3900   
4               9             3     4    0             0          3900   
5               7             4     4    0             0          3770   
6               0             4     4    1             0          3770   
...           ...           ...   ...  ...           ...           ...   
32556          10             1     4    1             0             0   
32557          12             5     4    0             0             0   
32558           6             0     4    1             0             0   
32559           0             4     4    0             0             0   
32560           0             3     4    1             0             0   

       hours_per_week  native_country  
1                  18              38  
3                  40              38  
4                  40              38  
5                  45              38  
6                  40              38  
...               ...             ...  
32556              40              38  
32557              38              38  
32558              40              38  
32559              40              38  
32560              20              38  

[30718 rows x 14 columns]

In [26]:
y

1        0
3        0
4        0
5        0
6        0
        ..
32556    0
32557    0
32558    1
32559    0
32560    0
Name: income, Length: 30718, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.79248046875


In [29]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8059895833333334


In [30]:
# hyperparameter tuning
from sklearn.model_selection import GridSearchCV

param_grid= {
    'criterion':['gini','entropy'],
    'max_depth':[2, 5, 10, None],
    'min_samples_leaf':[1,  5, 6, 2],
    'min_samples_split':[1,  5, 6, 2],
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)

grid_search.fit(x_train, y_train)



/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
160 fits failed out of a total of 640.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
160 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/tree/_classes.py", line 889, in fit
    super().fit(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/tree/_classes.py", line 177, in fit
    self._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 600, in _vali

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 5, 10, None],
                         'min_samples_leaf': [1, 5, 6, 2],
                         'min_samples_split': [1, 5, 6, 2]})

In [31]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 10,
 'min_samples_leaf': 5,
 'min_samples_split': 2}

In [32]:
grid_search.best_score_

0.8503704283358404

In [33]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf=1, min_samples_split=2)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8499348958333334


In [34]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[4244  395]
 [ 527  978]]


In [35]:
from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.91      0.90      4639
           1       0.71      0.65      0.68      1505

    accuracy                           0.85      6144
   macro avg       0.80      0.78      0.79      6144
weighted avg       0.85      0.85      0.85      6144



In [36]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8533528645833334


In [37]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[4326  313]
 [ 588  917]]


In [38]:
from sklearn.metrics import classification_report

print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.93      0.91      4639
           1       0.75      0.61      0.67      1505

    accuracy                           0.85      6144
   macro avg       0.81      0.77      0.79      6144
weighted avg       0.85      0.85      0.85      6144



In [39]:
from sklearn.model_selection import GridSearchCV

param_grid ={
    'n_estimators': [100, 200, 300],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]})

In [40]:
grid_search.best_params_ , grid_search.best_score_

({'criterion': 'gini',
  'max_depth': None,
  'min_samples_leaf': 2,
  'min_samples_split': 10,
  'n_estimators': 300},
 0.8607879743179844)

In [49]:
model = RandomForestClassifier(criterion='gini', max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=300)
model.fit(x_train, y_train)

RandomForestClassifier(min_samples_leaf=2, min_samples_split=10,
                       n_estimators=300)

In [52]:

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.8624674479166666
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      4639
           1       0.78      0.60      0.68      1505

    accuracy                           0.86      6144
   macro avg       0.83      0.78      0.80      6144
weighted avg       0.86      0.86      0.86      6144

Confusion Matrix:
[[4389  250]
 [ 595  910]]


In [55]:
# boosting
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)

Accuracy: 0.8562825520833334
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.94      0.91      4639
           1       0.77      0.59      0.67      1505

    accuracy                           0.86      6144
   macro avg       0.82      0.77      0.79      6144
weighted avg       0.85      0.86      0.85      6144

Confusion Matrix:
[[4371  268]
 [ 615  890]]


In [56]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.85986328125
Confusion Matrix:
[[4413  226]
 [ 635  870]]


In [45]:
# pip install xgboost

In [57]:
import xgboost as xgb

model = xgb.XGBClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.87109375
Confusion Matrix:
[[4351  288]
 [ 504 1001]]


In [47]:
# !pip install pycaret

In [48]:
# from pycaret.classification import *

# clf_setup = setup(data=dataframe, target='income')

# best_model = compare_models()